<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <AnalysisLevel>latest</AnalysisLevel>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <RepositoryUrl>https://github.com/Anezium/Dwmfix</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
</Project>
